# -*- coding: utf-8 -*-
"""ContactBookMenu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHStLVud-7JM2Ulvm0oiXSYgMxixDlI1
"""

contacts = {}

def show_menu():
  print('---Conctact Book Menu---')
  print('1. Add new contact')
  print('2. Search contact')
  print('3. Edit contact')
  print('4. Delete contact')
  print('5. View contacts')
  print('6. Exit')

def add_contact():
  name = input('Enter name: ')
  phone = input('Enter phone: ')
  email = input('Enter email: ')
  contacts[name] = {'phone': phone, 'email': email}
  print(f"Contact {name} has been added to your contact book successfully")

def search_contact():
  name = input('Enter the name of the contact you want to search: ')
  if name in contacts:
    print(f"---{name}'s Contact---")
    print(f"Phone: {contacts[name]['phone']}")
    print(f"Email: {contacts[name]['email']}")
  else:
    print(f"{name} is not in your contact book.")

def edit_contact():
  name = input('Enter the name of the contact you want to edit: ')
  if name in contacts:
    print(f"---Editing {name}'s Contact---")
    phone = input('Enter new phone: ')
    email = input('Enter new email: ')
    contacts[name] = {'phone': phone, 'email': email}
    print(f"{name}'s contact has been updated successfully")
  else:
    print(f"{name} is not in your contact book")

def delete_contact():
  name = input('Enter the name of the contact you want to delete: ')
  if name in contacts:
    del contacts[name]
    print(f"{name}'s contact has been deleted successfully")
  else:
    print(f"{name} is not in your contact book")

def view_contacts():
  if contacts:
    print('---Contacts---')
    for name, details in contacts.items():
      print(f"Name: {name}")
      print(f"Phone: {details['phone']}")
      print(f"Email: {details['email']}")
      print('-' * 20)
  else:
    print('Your contact book is empty')

while True:
  show_menu()
  choice = input('Enter your choice: ')
  if choice == '1':
    add_contact()
  elif choice == '2':
    search_contact()
  elif choice == '3':
    edit_contact()
  elif choice == '4':
    delete_contact()
  elif choice == '5':
    view_contacts()
  elif choice == '6':
    print('Exiting the program. Goodbye!')
    break
  else:
    print('Invalid choice. Please try again.')

import json
def save_contacts():
    with open('/content/contacts.json', 'w') as f:
        json.dump(contacts, f)

save_contacts()