# -*- coding: utf-8 -*-
"""Countdown Timer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6jdxKRmpWrPyYSZoi3GFKoKCzAybZCq
"""

import time

sleep_duration = int(input("Please enter the time sleep value: "))
start = int(input("Enter the number to start the countdown from: "))

original_start = start
half_point = original_start // 2

print("------Countdown Begins-------")
while start > 0:
    print(start)

    if start == half_point:
        print("--Yarısına Geldik--")

    start -= 1
    time.sleep(sleep_duration)

print("------Countdown Complete!-------")

# for variable in range(start, stop, step)
  # Code to repeat

for i in range(5, 0, -1):
  print(i)

while condition:
  # Code to repeat

count = 0
while count < 5:
  print(count)
  count += 1

import time

for i in range(10, 0, -2):
  print(i)
  time.sleep(1)
print("Happy New Year !")