# -*- coding: utf-8 -*-
"""Dayı1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xi5EKqt6o7nmdgRBKBGieXwkS_AGuulV
"""

print("Merhaba Dünya")

name = "Emre"
age = 15
height = 5.8
is_gamer = False

print(name)
print(age)
print(height)
print(is_gamer)

user_name = input("What is your name")
print("Welcome,"  + user_name +  "!")

age = int(input("How old are you?  "))
if age >= 18:
  print("You are an adult")
elif age >=13:
  print("You are a teenager")
else:
  print("Your are a Child")

def say_hello(person_name):
  print("Hello , " + person_name)

say_hello("Emre")

import random
secret_number = random.randint(1,10)
attempts = 3

print("I am thinking of a number between 1 and 10")
while attempts > 0:
  guess = int(input("Take a Guess: "))
  if guess == secret_number:
    print("Congratulations! You guessed the number!")
    break
  elif guess < secret_number:
   print("Too low! Try again.")
  else:
   print("Too high! Try again.")
attempts -= 1
if attempts == 0:
  print("Deneme hakkınız bitti")

import datetime
user_name2 = input("What is your name")
hobby = input("What is your hobby " )
date = datetime.datetime.now()

print("----Welcome Message----")
print(f"Hello,  {name.upper()}!")
print("Welcome to the world of python programming. " + str(date))