# -*- coding: utf-8 -*-
"""Day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZ2SBqCC1mhLjarOQdrbvzMTQr6O4cRf
"""

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

# En büyük sayıyı bulma
if num1 > num2 and num1 > num3:
    print(num1, "is the largest number")
elif num2 > num1 and num2 > num3:
    print(num2, "is the largest number")
else:
    print(num3, "is the largest number")

# Pozitiflik ve negatiflik kontrolü
if num1 > 0 and num2 > 0 and num3 > 0:
    print("All the three numbers are positive")
elif num1 < 0 and num2 < 0 and num3 < 0:
    print("All the three numbers are negative")
elif num1 == 0 and num2 == 0 and num3 == 0:
    print("All the three numbers are zero")
elif (num1 > 0 and num2 > 0 and num3 <= 0) or \
     (num1 > 0 and num3 > 0 and num2 <= 0) or \
     (num2 > 0 and num3 > 0 and num1 <= 0):
    print("Only two numbers are positive")