# -*- coding: utf-8 -*-
"""İngredientsChecker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLqMFr4fKE3Shxp3_WYyejkihHskjRnu
"""

# Malzeme Kontrol Programı

# 1. Tarif için gereken malzemeler
tarif_malzemeleri = {"un", "şeker", "tereyağı", "yumurta", "süt"}

# 2. Kullanıcıdan malzemeleri al
kullanici_girdisi = input("Elinizdeki malzemeleri girin (virgül ve boşluk ile ayırın, örnek: un, süt, yumurta): ")
kullanici_malzemeleri = set(kullanici_girdisi.split(", "))

# 3. Karşılaştırma yap
eksik_malzemeler = tarif_malzemeleri - kullanici_malzemeleri
fazla_malzemeler = kullanici_malzemeleri - tarif_malzemeleri

# 4. Sonuçları göster
print("\n--- Malzeme Kontrol Sonuçları ----")

if eksik_malzemeler:
    print(f"🧂 Eksik malzemeler: {', '.join(eksik_malzemeler)}")
else:
    print("✅ Gerekli tüm malzemelere sahipsiniz.")

if fazla_malzemeler:
    print(f"🧁 Fazladan malzemeleriniz var: {', '.join(fazla_malzemeler)}")
else:
    print("✅ Fazla malzemeniz yok.")

# Tuple (Demet) örneği
meyveler = ("elma", "muz", "kiraz")
print(f"Meyve sayısı: {len(meyveler)}")
print("Yeni meyve eklenmiş hali:", meyveler + ("portakal",))

# Set (Küme) örnekleri
malzemeler = {"un", "şeker", "tereyağı"}
print("Başlangıç malzemeleri:", malzemeler)

malzemeler.add("yumurta")
malzemeler.remove("şeker")
print("Güncel malzemeler:", malzemeler)

# Küme işlemleri
kume_a = {"un", "şeker", "tereyağı"}
kume_b = {"şeker", "yumurta"}

print("Birleşim:", kume_a | kume_b)
print("Kesişim:", kume_a & kume_b)
print("Fark (sadece A'da olanlar):", kume_a - kume_b)