# -*- coding: utf-8 -*-
"""Not Yöneticisi.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d09GpIpdXWsCCNEGMkCVtwBeOb0OH62b
"""

ogrenci_skor = input("Skor giriniz")
skor = [int(score) for score in ogrenci_skor.split(",")]
print(skor)

notlar = [
    "A" if score >= 90 else
    "B" if score >= 80 else
    "C" if score >= 70 else
    "D" if score >= 60 else
    "F" for score in skor
]

gecen_ogrenci = [score for score in skor if score >= 60]
kalan_ogrenci = [score for score in skor if score < 60]

ortalama = sum(skor) / len(skor)

print("Öğrenci Notları")
for i, (score, grade) in enumerate(zip(skor, notlar), start=1):
    print(f"{i}. Öğrenci Skoru: {score}, Notu: {grade}")

print("Geçen Öğrenciler", gecen_ogrenci)
print("Kalan Öğrenciler", kalan_ogrenci)
print("Sınıf Ortalaması", ortalama)
print("En Yüksek not", max(skor))
print("En Düşük not", min(skor))

kareler = [x**2 for x in range(10)]
print(kareler)

names = ["Emre", "Sait", "Buse", "Eliff"]
kısa_isim = [name for name in names if len(name) < 5]
print(kısa_isim)