# -*- coding: utf-8 -*-
"""Notes-TakeApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QH6x7OqYquiDVuUAaauE9uk6BkDzUKf-
"""

fıle_name = "myNotes.txt"

def show_menu():
  print("1. Add a note")
  print("2. List notes")
  print("3. Delete notes")
  print("4. Exit")

def add_note():
  note = input("Enter a note: ")
  with open(fıle_name, "a") as file:
    file.write(note + "\n")

def list_notes():
  with open(fıle_name, "r") as file:
    notes = file.readlines()
    for note in notes:
      print(note)

def delete_note():
    confirim = input("Are you sure you want to delete all notes? (y/n): ")
    if confirim.lower() == "y":
      with open(fıle_name, "w") as file:
        pass
        print("All notes deleted.")
    else:
      print("Deletion canceled.")


while True:
  show_menu()
  choice = input("Enter your choice: ")
  if choice == "1":
    add_note()
  elif choice == "2":
    list_notes()
  elif choice == "3":
    delete_note()
  else:
    print("Exiting...")
    break

with open("filename.txt", "r") as file:
  content = file.read()
  print(content)

with open("filename.txt", "w") as file:
  file.write("\nHello, World!\n")

with open("filename.txt", "a") as file:
  file.write("\nHello, My World!\n")