# -*- coding: utf-8 -*-
"""SafeCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uEkQCF-KqeBAYhJbcI8IxwOAQ5JJaB0
"""

# Safe Calculator

# Step 1 : Define Calculator Functions
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        raise ZeroDivisionError("Error: Division by zero is not allowed")
    return x / y

# Step 2 : Display Menu
def show_menu():
    print("\nSelect an operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")

# Step 3 : Main Program
while True:
    show_menu()
    choice = input("Enter your choice (1/2/3/4) : ")

    try:
        num1 = float(input("Enter first number : "))
        num2 = float(input("Enter second number : "))

        if choice == '1':
            result = add(num1, num2)
        elif choice == '2':
            result = subtract(num1, num2)
        elif choice == '3':
            result = multiply(num1, num2)
        elif choice == '4':
            result = divide(num1, num2)
        else:
            print("Invalid choice. Please select a valid operation.")
            continue

        print("Result:", result)

    except ValueError:
        print("Invalid input. Please enter valid numbers.")
    except ZeroDivisionError as e:
        print(e)
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
    finally:
        print("Thank you for using the safe calculator! Restarting...\n")

try:
  num = int(input("Enter a number :"))
  result = 10/ num
  print("Result ", result)
except ZeroDivisionError:
  print("Error: Division by zero is not allowed.")
except ValueError:
  print("Error: Invalid input. Please enter a valid number")

def withdraw(amount):
  if amount < 0:
    raise ValueError("Invalid withdrawal amount")
  print(f"You have withdrawn ${amount}")
try:
  withdraw(-50)
except ValueError as e:
  print(e)