# -*- coding: utf-8 -*-
"""ShoppingListApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddSsy6OqrhLhXIu6KuS5_WVCSJG9DVDQ
"""

# Shopping List App

shopping_list = []

def show_menu():
    print("-----Shopping List Menu------")
    print("1. View list")
    print("2. Add item")
    print("3. Remove item")
    print("4. Clear list")
    print("5. Exit")

while True:
  show_menu()
  choice = input("Enter your choice: ")
  if choice == "1":
    print("-----Shopping List-----")
    if not shopping_list:
      print("Your list is empty")
    else:
      for index, item in enumerate(shopping_list):
        print(f"{index + 1}. {item}")
  elif choice == "2":
    item = input("Enter item to add: ")
    shopping_list.append(item)
    print(f"{item} has been added to the list")

  elif choice == "3":
    item = input("Enter item to remove: ")
    if item in shopping_list:
      shopping_list.remove(item)
      print(f"{item} has been removed from the list")
    else:
      print(f"{item} is not in the list")
  elif choice == "4":
    shopping_list.clear()
    print("List has been cleared")
  elif choice == "5":
    print("Exiting program")
    break



with open('/content/a.txt', 'w') as fp:
    for item in shopping_list:
        fp.write(item + '\n')

shopping_list = ["Milk", "Eggs", "Bread"]
print(shopping_list)

print(shopping_list[1])

shopping_list.append("Cheese")
shopping_list.insert(0, "Bananas")
print(shopping_list)

shopping_list.remove("Eggs")
print(shopping_list)

shopping_list.pop()
print(shopping_list)

for item in shopping_list:
    print(f" - {item}")

shopping_list.sort()
print(shopping_list)

shopping_list.reverse()
print(shopping_list)